name: mvsc-py39
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - numpy
  - pillow
  - pip
  - pip:
      - timm>=0.6.13,<1.0
